name: CI

on:
  pull_request:
    branches: ['master']

  push:
    branches: ['master']

jobs:
  code-analysis:
    name: Code Analysis
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/setup-node@v3
        with:
          node-version: 20
          cache: 'pnpm'
      - run: pnpm
      - run: pnpm build
